validate:
  image: gramener/builderrors
  script: builderrors

deploy:
  stage: deploy
  script: deploy
  variables:
    SERVER: gramener.com
    URL: videohighlights
    VERSION: static
    SETUP: npm install --only=production
    CORS: enabled
  environment:
    name: production
    url: https://gramener.com/videohighlights/
